apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.todoapp.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
