
common:
  namespace: mysql


mysql:
  image:
    repository: mysql
    version: 8.0

  replicas: 2

  secrets:
    MYSQL_ROOT_PASSWORD: "MTIzNA=="
    MYSQL_USER: "YXBwX3VzZXI="
    MYSQL_PASSWORD: "MTIzNA=="

  resource:
    requests:
      cpu: 500m
      memory: 1Gi

  pvc:
    requests:
      storage: 2Gi

  tolerations:
    key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

  affinity:
    podAntiAffinity:
      key: app
      operator: In
      values:
       - mysql

    nodeAntiAffinity:
      key: app
      operator: In
      values:
       - mysql
