apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
