apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: mysql
type: Opaque
data:
  {{- range $k, $v := .Values.mysql.secrets }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
