apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.mysql.replicas }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.version}}
        env:
        - name: MYSQL_DATABASE
          value: app_db
        {{- range $key, $value := .Values.mysql.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-secrets
              key: {{ $key }}
        {{- end }}
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: {{ .Values.mysql.resource.requests.cpu }}
            memory: {{ .Values.mysql.resource.requests.memory }}
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: config-map
        configMap:
          name: mysql
      tolerations:
      - key: {{ .Values.mysql.tolerations.key | quote }}
        operator: {{ .Values.mysql.tolerations.operator | quote }}
        value: {{ .Values.mysql.tolerations.value | quote }}
        effect: {{ .Values.mysql.tolerations.effect | quote }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: {{ .Values.mysql.affinity.podAntiAffinity.key }}
                    operator: {{ .Values.mysql.affinity.podAntiAffinity.operator }}
                    values:
                    {{- range .Values.mysql.affinity.podAntiAffinity.values }}
                     - {{ . | quote }}
                    {{- end }}
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.mysql.affinity.nodeAntiAffinity.key }}
                    operator: {{ .Values.mysql.affinity.nodeAntiAffinity.operator }}
                    values:
                    {{- range .Values.mysql.affinity.nodeAntiAffinity.values }}
                     - {{ . | quote }}
                    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.pvc.requests.storage }}
