
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: {{ .Values.common.namespace }}
spec:
  volumeName: pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.todoapp.pvc.resources.requests.storage }}
